require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# to run app with Flipper
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)

      if text != replace
          puts "Fix: " + name
          system("chmod +w " + name)
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

target 'Habitsapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)
  


  target 'HabitsappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' , 'Flipper' => '0.88.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  #   find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
  #         "  atomic_notify_one(state);", "  folly::atomic_notify_one(state);")
  # end
end

